stages:
  - build
  - deploy

variables:
  CONTAINER_NAME: news-ui-user
  CI_REGISTRY_DEV: 10.208.50.7:5000
  DOCKER_IMAGE: ${CI_REGISTRY_DEV}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_SLUG}

build:
  tags:
    - comunity
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_DEV
  script:
    - docker stop $CONTAINER_NAME || true &&
    - docker rm $CONTAINER_NAME || true &&
    - docker rmi -f $DOCKER_IMAGE || true &&
    - docker build -t $DOCKER_IMAGE -f Dockerfile .
    - docker rmi $(docker images --filter "dangling=true" -q) || true
  only:
    - develop
    
deploy:
  tags:
    - comunity
  stage: deploy
  image: alpine:latest
  script:
    - |
        docker run -d --name $CONTAINER_NAME --network news-network -p 3016:3016 --restart unless-stopped $DOCKER_IMAGE
  only:
    - develop